using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MyFeeds.Clients
{
    public class VintedSizes
    {
        public static string Tailles_XS { get { return "206"; } }
        public static string Tailles_S { get { return "207"; } }
        public static string Tailles_M { get { return "208"; } }
        public static string Tailles_L { get { return "209"; } }
        public static string Tailles_XL { get { return "210"; } }
        public static string Tailles_XXL { get { return "211"; } }
        public static string Tailles_XXXL { get { return "212"; } }
        public static string Tailles_4XL { get { return "308"; } }
        public static string Tailles_5XL { get { return "309"; } }
        public static string Tailles_6XL { get { return "1192"; } }
        public static string Tailles_8XL { get { return "1194"; } }
        public static string Tailles_Taille_unique { get { return "213"; } }
        public static string Pantalons_W23_FR_32 { get { return "1631"; } }
        public static string Pantalons_W24_FR_34 { get { return "1632"; } }
        public static string Pantalons_W25_FR_34 { get { return "1633"; } }
        public static string Pantalons_W26_FR_36 { get { return "1634"; } }
        public static string Pantalons_W27_FR_36 { get { return "1635"; } }
        public static string Pantalons_W28_FR_38 { get { return "1636"; } }
        public static string Pantalons_W29_FR_38 { get { return "1637"; } }
        public static string Pantalons_W30_FR_40 { get { return "1638"; } }
        public static string Pantalons_W31_FR_40 { get { return "1639"; } }
        public static string Pantalons_W32_FR_42 { get { return "1640"; } }
        public static string Pantalons_W33_FR_42 { get { return "1641"; } }
        public static string Pantalons_W34_FR_44 { get { return "1642"; } }
        public static string Pantalons_W35_FR_44 { get { return "1662"; } }
        public static string Pantalons_W36_FR_46 { get { return "1643"; } }
        public static string Pantalons_W38_FR_48 { get { return "1644"; } }
        public static string Pantalons_W40_FR_50 { get { return "1645"; } }
        public static string Pantalons_W42_FR_52 { get { return "1646"; } }
        public static string Pantalons_W44_FR_54 { get { return "1647"; } }
        public static string Pantalons_W46_FR_56 { get { return "1648"; } }
        public static string Pantalons_W48_FR_58 { get { return "1649"; } }
        public static string Pantalons_W50_FR_60 { get { return "1704"; } }
        public static string Pantalons_W54_FR_64 { get { return "1706"; } }
        public static string Pantalons_XS { get { return "1650"; } }
        public static string Pantalons_S { get { return "1651"; } }
        public static string Pantalons_M { get { return "1652"; } }
        public static string Pantalons_L { get { return "1653"; } }
        public static string Pantalons_XL { get { return "1654"; } }
        public static string Pantalons_XXL { get { return "1655"; } }
        public static string Pantalons_XXXL { get { return "1656"; } }
        public static string Pantalons_4XL { get { return "1657"; } }
        public static string Chemises_XS { get { return "1545"; } }
        public static string Chemises_S { get { return "1546"; } }
        public static string Chemises_M { get { return "1547"; } }
        public static string Chemises_L { get { return "1548"; } }
        public static string Chemises_XL { get { return "1549"; } }
        public static string Chemises_XXL { get { return "1550"; } }
        public static string Chemises_XXXL { get { return "1551"; } }
        public static string Chemises_4XL { get { return "1552"; } }
        public static string Chemises_5XL { get { return "1553"; } }
        public static string Chemises_37_cm { get { return "1529"; } }
        public static string Chemises_38_cm { get { return "1530"; } }
        public static string Chemises_39_cm { get { return "1531"; } }
        public static string Chemises_40_cm { get { return "1532"; } }
        public static string Chemises_41_cm { get { return "1533"; } }
        public static string Chemises_42_cm { get { return "1534"; } }
        public static string Chemises_43_cm { get { return "1535"; } }
        public static string Chemises_44_cm { get { return "1536"; } }
        public static string Chemises_45_cm { get { return "1537"; } }
        public static string Chemises_46_cm { get { return "1538"; } }
        public static string Chemises_47_cm { get { return "1539"; } }
        public static string Chemises_50_cm { get { return "1542"; } }
        public static string Vestes_XS { get { return "1609"; } }
        public static string Vestes_S { get { return "1610"; } }
        public static string Vestes_M { get { return "1611"; } }
        public static string Vestes_L { get { return "1612"; } }
        public static string Vestes_XL { get { return "1613"; } }
        public static string Vestes_XXL { get { return "1614"; } }
        public static string Vestes_XXXL { get { return "1615"; } }
        public static string Vestes_5XL { get { return "1617"; } }
        public static string Vestes_42 { get { return "1592"; } }
        public static string Vestes_44 { get { return "1593"; } }
        public static string Vestes_46 { get { return "1594"; } }
        public static string Vestes_48 { get { return "1595"; } }
        public static string Vestes_50 { get { return "1596"; } }
        public static string Vestes_52 { get { return "1597"; } }
        public static string Vestes_54 { get { return "1598"; } }
        public static string Vestes_56 { get { return "1599"; } }
        public static string Vestes_58 { get { return "1600"; } }
        public static string Vestes_110 { get { return "1606"; } }
        public static string Chaussuress_38 { get { return "776"; } }
        public static string Chaussuress_38_5 { get { return "777"; } }
        public static string Chaussuress_39 { get { return "778"; } }
        public static string Chaussuress_39_5 { get { return "779"; } }
        public static string Chaussuress_40 { get { return "780"; } }
        public static string Chaussuress_40_5 { get { return "781"; } }
        public static string Chaussuress_41 { get { return "782"; } }
        public static string Chaussuress_41_5 { get { return "783"; } }
        public static string Chaussuress_42 { get { return "784"; } }
        public static string Chaussuress_42_5 { get { return "785"; } }
        public static string Chaussuress_43 { get { return "786"; } }
        public static string Chaussuress_43_5 { get { return "787"; } }
        public static string Chaussuress_44 { get { return "788"; } }
        public static string Chaussuress_44_5 { get { return "789"; } }
        public static string Chaussuress_45 { get { return "790"; } }
        public static string Chaussuress_45_5 { get { return "791"; } }
        public static string Chaussuress_46 { get { return "792"; } }
        public static string Chaussuress_46_5 { get { return "793"; } }
        public static string Chaussuress_47 { get { return "794"; } }
        public static string Chaussuress_47_5 { get { return "795"; } }
        public static string Chaussuress_48 { get { return "1190"; } }
        public static string Chaussuress_48_5 { get { return "1621"; } }
        public static string Chaussuress_49 { get { return "1191"; } }
        public static string Chaussuress_50 { get { return "1327"; } }
        public static string Chaussuress_Taille_unique { get { return "1624"; } }
        public static string Chaussuress_Autre { get { return "1625"; } }
        public static string Bagues_14_1_mm { get { return "1202"; } }
        public static string Bagues_14_5_mm { get { return "1203"; } }
        public static string Bagues_14_9_mm { get { return "1204"; } }
        public static string Bagues_15_3_mm { get { return "1205"; } }
        public static string Bagues_15_7_mm { get { return "1206"; } }
        public static string Bagues_16_1_mm { get { return "1207"; } }
        public static string Bagues_16_5_mm { get { return "1208"; } }
        public static string Bagues_16_9_mm { get { return "1209"; } }
        public static string Bagues_17_3_mm { get { return "1210"; } }
        public static string Bagues_17_7_mm { get { return "1211"; } }
        public static string Bagues_18_1_mm { get { return "1212"; } }
        public static string Bagues_18_5_mm { get { return "1213"; } }
        public static string Bagues_19_mm { get { return "1214"; } }
        public static string Bagues_19_4_mm { get { return "1215"; } }
        public static string Bagues_19_8_mm { get { return "1216"; } }
        public static string Bagues_20_2_mm { get { return "1217"; } }
        public static string Bagues_20_6_mm { get { return "1218"; } }
        public static string Bagues_21_mm { get { return "1219"; } }
        public static string Bagues_21_4_mm { get { return "1220"; } }
        public static string Bagues_22_2_mm { get { return "1222"; } }
        public static string Bagues_Ajustable { get { return "1224"; } }
        public static string Chapeaux_XS { get { return "1388"; } }
        public static string Chapeaux_S { get { return "1389"; } }
        public static string Chapeaux_M { get { return "1390"; } }
        public static string Chapeaux_L { get { return "1391"; } }
        public static string Chapeaux_XL { get { return "1392"; } }
        public static string Chapeaux_Taille_unique { get { return "1387"; } }
        public static string Chapeaux_52 { get { return "1373"; } }
        public static string Chapeaux_53 { get { return "1374"; } }
        public static string Chapeaux_54 { get { return "1375"; } }
        public static string Chapeaux_55 { get { return "1376"; } }
        public static string Chapeaux_56 { get { return "1377"; } }
        public static string Chapeaux_57 { get { return "1378"; } }
        public static string Chapeaux_58 { get { return "1379"; } }
        public static string Chapeaux_59 { get { return "1380"; } }
        public static string Chapeaux_60 { get { return "1381"; } }
        public static string Montres_Moins_de_30_mm { get { return "1429"; } }
        public static string Montres_30_a_38_mm { get { return "1430"; } }
        public static string Montres_39_a_42_mm { get { return "1431"; } }
        public static string Montres_43_a_46_mm { get { return "1432"; } }
        public static string Montres_47_mm_et_plus { get { return "1433"; } }
        public static string Montres_Taille_unique { get { return "1435"; } }
        public static string Gants_5 { get { return "1408"; } }
        public static string Gants_6 { get { return "1410"; } }
        public static string Gants_7 { get { return "1412"; } }
        public static string Gants_7_5 { get { return "1413"; } }
        public static string Gants_8 { get { return "1414"; } }
        public static string Gants_8_5 { get { return "1415"; } }
        public static string Gants_9 { get { return "1416"; } }
        public static string Gants_10 { get { return "1418"; } }
        public static string Gants_12 { get { return "1422"; } }
        public static string Gants_Taille_unique { get { return "1423"; } }
        public static string Gants_XS { get { return "1424"; } }
        public static string Gants_S { get { return "1425"; } }
        public static string Gants_M { get { return "1426"; } }
        public static string Gants_L { get { return "1427"; } }
        public static string Gants_XL { get { return "1428"; } }
        public static string Ceintures_70_cm { get { return "1702"; } }
        public static string Ceintures_80_cm { get { return "1436"; } }
        public static string Ceintures_85_cm { get { return "1437"; } }
        public static string Ceintures_90_cm { get { return "1438"; } }
        public static string Ceintures_95_cm { get { return "1439"; } }
        public static string Ceintures_100_cm { get { return "1440"; } }
        public static string Ceintures_105_cm { get { return "1441"; } }
        public static string Ceintures_110_cm { get { return "1442"; } }
        public static string Ceintures_115_cm { get { return "1443"; } }
        public static string Ceintures_120_cm { get { return "1444"; } }
        public static string Ceintures_125_cm { get { return "1445"; } }
        public static string Ceintures_130_cm { get { return "1726"; } }
        public static string Ceintures_Ajustable { get { return "1581"; } }
        public static string Chaussettes_XS_36_a_37 { get { return "1522"; } }
        public static string Chaussettes_S_38_a_42 { get { return "1523"; } }
        public static string Chaussettes_M_43_a_46 { get { return "1524"; } }
        public static string Chaussettes_L_47_a_52 { get { return "1525"; } }
        public static string Chaussettes_Taille_unique { get { return "1526"; } }

    }
}
